schemaVersion: 2.2.0
metadata:
  generateName: ${{values.component_id}}
components:
  - name: tools
    container:
      image: quay.io/devfile/universal-developer-image:ubi8-latest
      env:
        - name: GOPATH
          value: /projects:/home/user/go
        - name: GOCACHE
          value: /tmp/.cache
      endpoints:
        - name: 9000-http
          targetPort: 9000
          protocol: http
      memoryLimit: 2Gi
      mountSources: true

commands:
  - id: run-api
    exec:
      label: "1.1 Run api"
      component: tools
      workingDir: ${PROJECT_SOURCE}
      commandLine: "go get -d && go run main.go"
      group:
        kind: run

  - id: stop-api
    exec:
      label: "1.2 Stop api"
      component: tools
      commandLine: "kill $(pidof go)"
      group:
        kind: run

  - id: test-outyet
    exec:
      label: "1.3 Test api"
      component: tools
      workingDir: ${PROJECT_SOURCE}
      commandLine: "go test"
      group:
        kind: test

  - id: run-current-file
    exec:
      label: "Run current file"
      component: tools
      workingDir: ${fileDirname}
      commandLine: "go get -d && go run ${file}"
      group:
        kind: run
