{{- with .Values.route }}
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  labels:
    {{- include "nodejs-template.labels" $ | nindent 4 }}
  name: ${{values.component_id}}
spec:
  {{- if .host }}
  host: {{ .host }}
  {{- end }}
  {{- if .path }}
  path: {{ .path }}
  {{- end }}
  port:
    targetPort: {{ $.Values.service.port }}
  to:
    kind: Service
    name: ${{values.component_id}}
  tls:
    termination: edge
  wildcardPolicy: None
{{- end }}
