apiVersion: scaffolder.backstage.io/v1beta3
kind: Template
metadata:
  name: coolstore-gateway-template
  title: Gateway microservice with Vertx (Coolstore)
  description: Create a Vertx microservice for Gateway built on a trusted software supply chain
  tags:
    - coolstore
    - demo
    - java
    - vertx
    - maven
spec:
  owner: rhdh
  type: service
  parameters:
    - title: Provide Information for Application
      required:
        - application_id
        - cluster_id
        - namespace
      properties:
        application_id:
          title: Name
          type: string
          description: Unique name of the application
          default: gateway-vertx
          ui:field: EntityNamePicker
          maxLength: 32
        description:
          title: Description
          type: string
          description: Help others understand what this website is for.
          default: Gateway microservice for Coolstore
        cluster_id:
          title: Cluster Id
          type: string
          description: Id of the cluster
          default: .apps.cluster-679vg.sandbox121.opentlc.com
        namespace:
          title: Namespace
          type: string
          description: Namespace
          default: coolstore
    - title: Provide Image Registry Information
      required:
        - image_registry
      properties:
        image_registry:
          title: Image Registry
          type: string
          enum:
            - Openshift
            - Quay
      dependencies:
        image_registry:
          oneOf:
            - properties:
                image_registry:
                  enum:
                    - Openshift
                image_host:
                  title: Image Host
                  type: string
                  description: Host for storing image
                  default: image-registry.openshift-image-registry.svc:5000
                image_tag:
                  title: Image Tag
                  default: latest
                  type: string
                  description: Build Image tag
            - properties:
                image_registry:
                  enum:
                    - Quay
                image_host:
                  title: Image Host
                  type: string
                  description: Host for storing image
                  default: quay-679vg.apps.cluster-679vg.sandbox121.opentlc.com
                image_organization:
                  title: Organization
                  type: string
                  description: Name of the Quay Organization
                  default: quayadmin
                image_tag:
                  title: Image Tag
                  default: latest
                  type: string
                  description: Build Image tag
    - title: Application repository Information
      required:
        - repo
      properties:
        repo:
          title: Repository Location
          type: object
          properties:
            host:
              title: Repo Host
              type: string
              description: Your SCM host
              default: gitlab-gitlab.apps.cluster-679vg.sandbox121.opentlc.com
            owner:
              title: Repo Owner
              type: string
              description: Your SCM host organization/group
              default: development
              enum:
                - development

  steps:
    - id: template
      name: Fetch Skeleton + Template
      action: fetch:template
      input:
        url: ./skeleton
        copyWithoutTemplating:
          - .github/workflows/*
        values:
          component_id: ${{ parameters.namespace }}-${{ parameters.application_id }}
          description: ${{ parameters.description }}
          namespace_raw: ${{ parameters.namespace }}
          namespace: ${{ parameters.namespace }}-dev
          owner: ${{ user.entity.metadata.name }}
          cluster: ${{ parameters.cluster_id }}
          host: ${{ parameters.repo.host }}
          destination: ${{ parameters.repo.owner }}/${{ parameters.namespace }}-${{ parameters.application_id }}
          quay_destination: ${{ parameters.image_organization}}/${{ parameters.namespace }}-${{ parameters.application_id }}
          port: 8080

    - id: publish
      name: Publish
      action: publish:gitlab
      input:
        repoUrl: "${{ parameters.repo.host }}?owner=${{ parameters.repo.owner }}&repo=${{ parameters.namespace }}-${{ parameters.application_id }}"
        repoVisibility: public

    - id: register
      name: Register
      action: catalog:register
      input:
        repoContentsUrl: ${{ steps.publish.output.repoContentsUrl }}
        catalogInfoPath: "/catalog-info.yaml"

    - id: template-gitops-deployment
      name: Generating Deployment Resources
      action: fetch:template
      input:
        url: ./manifests
        copyWithoutTemplating: []
        values:
          component_id: ${{ parameters.namespace }}-${{ parameters.application_id }}
          description: ${{ parameters.description }}
          destination: https://${{ parameters.repo.host }}/${{ parameters.repo.owner }}/${{ parameters.namespace }}-${{ parameters.application_id }}-gitops.git
          source_repository: https://${{ parameters.repo.host }}/${{ parameters.repo.owner }}/${{ parameters.namespace }}-${{ parameters.application_id }}.git
          repository_name: ${{ parameters.namespace }}-${{ parameters.application_id }}
          git_owner: ${{ parameters.repo.owner }}
          cluster: ${{ parameters.cluster_id }}
          namespace: ${{ parameters.namespace }}
          image_registry: ${{ parameters.image_registry }}
          image_host: ${{ parameters.image_host }}
          image_organization: ${{ parameters.image_organization }}
          image_name: ${{ parameters.namespace }}-${{ parameters.application_id }}
          image_tag: ${{ parameters.image_tag }}
          port: 8080
          repository_host: ${{ parameters.repo.host }}
          deployment_name: quarkus-template
          user: ${{ user.entity.metadata.name }}
        targetPath: ./tenant-gitops

    - id: publish-gitops
      name: Publishing to Resource Repository
      action: publish:gitlab
      input:
        repoUrl: "${{ parameters.repo.host }}?owner=${{ parameters.repo.owner }}&repo=${{ parameters.namespace }}-${{ parameters.application_id }}-gitops"
        title: gitops resources for ${{ parameters.namespace }}-${{ parameters.application_id }}
        description: gitops resources for ${{ parameters.namespace }}-${{ parameters.application_id }}
        sourcePath: ./tenant-gitops
        repoVisibility: public

    - id: create-argocd-resources
      name: Create ArgoCD Resources
      action: argocd:create-resources
      input:
        appName: ${{ parameters.namespace }}-${{ parameters.application_id }}-bootstrap
        argoInstance: main
        namespace: janus-argocd
        repoUrl: https://${{ parameters.repo.host }}/${{ parameters.repo.owner }}/${{ parameters.namespace }}-${{ parameters.application_id }}-gitops.git
        path: 'argocd/'

  output:
    links:
      - title: Source Code Repository
        url: ${{ steps.publish.output.remoteUrl }}
      - title: Open Component in catalog
        icon: catalog
        entityRef: ${{ steps.register.output.entityRef }}